### ISSUE TITLE
Add Social Media authentication 

### ISSUE THREAD

**Issue by Vrindagupta6828** [garg3133/JagratiWebApp#62] opened 2021-01-13 14:31 UTC
We can add authentication by various social networking handles like gmail, facebook etc.

**Comment by garg3133** [comment] 2021-01-13 14:36
Hey @Vrindagupta6828, thanks for raising this issue. I myself was thinking of adding this feature to the project for quite a long time.

**Comment by Vrindagupta6828** [comment] 2021-01-13 14:37
@garg3133 Please assign me this and tell me that with which sites i have to do social authentication

**Comment by garg3133** [comment] 2021-01-13 14:41
Sure @Vrindagupta6828!

You just need to add the social authentication with Google. See that an instance is created in the existing `User` model also (maybe with any randomly generated password) when the user signs up using Google auth.

Also, if an existing user wants to link his/her account with Google auth, he/she should be able to do so.

**Comment by Vrindagupta6828** [comment] 2021-01-19 15:27
@garg3133 can you please tell me what is the authorized domain of this application?

**Comment by garg3133** [comment] 2021-01-19 15:49
We're using https://jagrati.herokuapp.com for now.

**Comment by Vrindagupta6828** [comment] 2021-01-22 15:18
@garg3133 When the google accounts page after sign up is redirecting to the original jagrati webapp page i am facing this issue and i am unable to solve it can you please guide me.

ValueError at /social-auth/complete/google-oauth2/
User must have a password

**Comment by garg3133** [comment] 2021-01-22 16:39
@Vrindagupta6828 Which Python package are you using for oauth? I guess the problem is that oauth is trying to create a user without a password, which is not possible in our application. So you need to come up with something to create a random password and use it while creating a new user using oauth.

Also, you may open a [Work In Progress] PR to get better feedback.

**Comment by garg3133** [comment] 2021-01-29 10:03
Resolved in #74.

**Closed by garg3133** 2021-01-29 10:03 UTC
Labels: SWOC 2021, hard
